t6d/smart_properties

lib/smart_properties.rb
spec/smart_properties_spec.rb

Lambda statements provided to the default configuration option are no longer evaulated every time. Instead, they are only evaluated if no value for a particular property has been given.

Prevent unnecessary evaluation of default blocks

---

lib/smart_properties.rb
spec/smart_properties_spec.rb

Raises an InitializationError if a required but overridden property has not been set (even if the overridden method returns a non-nil value).

Initialization of required overridden properties

---

lib/smart_properties.rb
spec/smart_properties_spec.rb

Unmatched positional arguments are forwarded to the super class constructor.

Constructor argument forwarding

---

spec/support/smart_property_matcher.rb

The matcher now has a description and it further tests that the getter and setter of a property are defined.

Improved SmartPropertyMatcher

---

lib/smart_properties.rb
spec/base_spec.rb
spec/required_values_spec.rb

If a property is flagged as required, the converter must return a non-nil value.

Check for nil again after conversion

---

lib/smart_properties.rb

@t6d 
This gets around that issue we were running into, where we wanted to avoid calling `nil?` on the `value` if not absolutely necessary.
Note that the `convert` method already just returns if there's no converter: https://github.com/t6d/smart_properties/blob/7f04dd73270e7269f5a0cc3678c482688f45062b/lib/smart_properties.rb#L137.
For now, I just updated the problematic class in our private repo to not use `smart_properties` because this fix seems pretty fragile. But I figured I'd open a PR here to get your thoughts anyway.

Only convert if there is a converter

---

lib/smart_properties.rb
spec/inheritance_spec.rb

All keyword arguments that do not correspond to a property are forwarded to the super class constructor.

Forwarding of unprocessed options

---

lib/smart_properties.rb
spec/inheritance_spec.rb

Reverts t6d/smart_properties#26 due to unforeseen issues with `HashWithIndifferentAccess` instances. These hashes return the `keys` as they were originally inserted and potentially break the `properties.key?` check in the initializer.
The better solution would be to use the property collection instead of a `to_hash` version of this collection. To make this work, the property collection needs to implement caching for performance reasons.

Revert "Forwarding of unprocessed options"

---

lib/smart_properties/property_collection.rb
smart_properties.gemspec
spec/property_collection_caching_spec.rb
spec/spec_helper.rb

A PropertyCollection now keeps tracks of its children and updates them
whenever a new property is added to a class. This enables faster querying
for a particular property. Previously, this query would have caused walking
the entire PropertyCollection chain and merging several hashes.
Internally, a PropertyCollection references its properties using strings
because these are GCed. Assigning unsafe input to a SmartProperties enabled
object could otherwise lead to excisive memory usage because
PropertyCollection#key? would have to convert to a symbol which would not
be GCed.

Proper PropertyCollection caching

---

lib/smart_properties.rb
lib/smart_properties/property.rb
lib/smart_properties/property_collection.rb
smart_properties.gemspec
spec/base_spec.rb
spec/inheritance_spec.rb
spec/property_collection_caching_spec.rb
spec/spec_helper.rb

Improvements:
* `SmartProperties` enabled objects can now be intialized with hashes that use strings as keys.
* All keyword arguments that do not correspond to a property are now forwarded to the super class constructor.
* The performance of the initializer has been improved by reducing the number of instantiated helper objects.

Option Forwarding and Support for Strings as Keys

---

lib/smart_properties/errors.rb

This PR unifies the two spellings of `accepter` in `errors.rb` and simplifies the logic in `accepter_message`.

Unify `accepter` spelling, simplify logic.

---

lib/smart_properties/property.rb
spec/reader_spec.rb

Allows you to define a custom reader name for your property.
```Ruby
class Post
property :new, default: false, accepts: [true, false], reader: :new?
end
post = Post.new(new: false)
post.new? # false
post[:new] = true
post.new? # true
post[:new] # true
```

Add support for custom reader

---

README.md
lib/smart_properties.rb
spec/required_values_spec.rb

Closes https://github.com/t6d/smart_properties/issues/49
Add alternative notation `property!` method to define required arguments.
CC: @t6d

Add property! method to define required arguments

---

lib/smart_properties.rb
lib/smart_properties/errors.rb
spec/base_spec.rb

Introduces a new error: ConstructorArgumentForwardingError. This error gets raised when positional arguments or unknown additional keyword arguments get forwarded to the super class initializer which itself can’t process them.
FYI, @SebastianSzturo

ConstructorArgumentForwardingError

---

lib/smart_properties.rb
lib/smart_properties/property.rb

Moves `#[]` and `#[]=` definitions from `SmartProperties::Property::IndexMethods` into the main `SmartProperties` module.

Move index methods into the main module

---

README.md

Because it's not obvious that you should or even can use `super`.

add README section about overriding readers

---

lib/smart_properties/property.rb
spec/base_spec.rb

I ran into an issue when using properties that are ActiveRecord::Relation objects - essentially what was happening was extra queries being made to the database during smart property validation. It turns out that ActiveRecord (and probably other things) can have side effects when using the built-in equality methods.
This PR changes the order of the nil-checking for properties and uses the `#nil?` method as the default now; if a `NoMethodError` is raised, then we can safely do a nil singleton equality check since the object being validated is most likely descending from BasicObject.

Use equality test for nil as a last resort

---

lib/smart_properties/property_collection.rb
spec/property_collection_caching_spec.rb

There is an issue when prepending a module to a class that has`SmartProperties`. When `SmartProperties::PropertyCollection.for` is called, it will identify the class as a parent of itself. This
will cause a recursive ancestor check.
To fix this, I added a simple check in the parent identification to ensure that the ancestor is not the base class.

Fixing PropertyCollection to deal with prepended modules

---

.gitignore
lib/smart_properties/property.rb
spec/read_only_spec.rb
spec/writable_spec.rb

By default `property` creates both an accessor and a reader for the property.
Currently if you do not want a public accessor you have to do something similar to the following:
```ruby
class TestClass
property! :id
protected :id=
end
```
This proposed change allows the ability to make a property read only:
```ruby
class TestClass
property! :id, read_only: true
end
```
When using the `read_only` flag as `true` an accessor will not be created for that property.
If no `read_only` flag is provided the current default behaviour of creating an accessor will continue.

Adding writable as an option on property.

---

lib/smart_properties/property.rb
spec/base_spec.rb
spec/configuration_error_spec.rb
spec/default_values_spec.rb

I encountered an issue where a property with a default specified as `default: []` ends up being shared across all instances of the class where the property is defined. Adding elements to the array is reflected across other instances since the array is shared.
For example this would be the current behavior without this PR:
```ruby
class Foo
include SmartProperties
property :array,  default: []
end
a = Foo.new
b = Foo.new
a.array << 1
puts b.array # => [1]
puts b.array.object_id == a.array.object_id # => true
```
Likewise, this is possible:
```ruby
class Foo
include SmartProperties
property :string,  default: 'foo!'
end
a = Foo.new
b = Foo.new
a.string[0] = 'z'
puts b.string # => zoo!
a.string << 'moo'
puts b.string # => zoo!moo
```
These may be more common than we realize since the …

Prevent defaults that may be shared and mutated across all instances of a class

---

smart_properties.gemspec

By doing this, automated tools like dependabot can now find the repository based on the gem.

Add metadata for the source code

---

lib/smart_properties/property.rb
spec/configuration_error_spec.rb

Previously, these needed to be wrapped in a Proc, but it was pointless since
modules/classes are shared mutable state that's always intentionally shared/aliased.
This allows you to rewrite:
```ruby
property :strategy, accept: Ancestor.must_be(type: BaseStrategy), default: -> { DefaultStrategy }
```
... as just:
```
property :strategy, accept: Ancestor.must_be(type: BaseStrategy), default: DefaultStrategy
```

Allow Modules (and classes) as default values

---

lib/smart_properties.rb
lib/smart_properties/dsl.rb
lib/smart_properties/generic_accessors.rb
lib/smart_properties/initializer.rb
lib/smart_properties/plugin.rb
spec/plugin_spec.rb

Introduces a subclass of Module named `SmartProperties::Plugin` that enables the creation of plugins that know whether they need to include themselves or extend the target class.
```ruby
HelloPlugin = SmartProperties::Plugin.new(:include) do
def hello
"hello"
end
end
SomeClass = Class.new
HelloPlugin.attach(SomeClass)
HelloPlugin.new.hello # => "hello"
```
Co-authored-by: Vivek Wassan <vivek.wassan@shopify.com>

SmartProperties::Plugin

---

lib/smart_properties/property.rb

Clarify what the `(class << object; self; end)` trick does.
I also split apart the large comment into what is (IMO) a more readable form. WDYT?

Tweak comments on Property#null_object?

---

README.md

```ruby
Ancestor.must_be(Numeric)
```
fails with:
```
Forwarding the following positional argument failed: Numeric
```
You need the `type:` keyword label.

Add missing keyword to Ancestor.must_be

---

lib/smart_properties/plugins/generic_accessors.rb
spec/base_spec.rb

`#[]` and `#[]=` will now forward all arguments to the super class if
the provided arguments do not correspond to a property.
Closes #38.

Argument forwarding for generic accessors

---

lib/smart_properties.rb
lib/smart_properties/property_collection.rb
spec/inheritance_spec.rb

SmartProperties now allows modules to define properties just like classes do and ensures that all properties are eventually included into the target class. Multiple inheritance was previously not supported or required custom `included` hooks.
```ruby
module PII
include SmartProperties
property! :name, accepts: String
property! :email, accepts: String
end
module Job
property! :title, accepts: String
property! :company, accepts: String
end
class Person
include PII
include Job
end
```

Support for multiple inheritance

---

smart_properties.gemspec

Updates rake from Version 12 to Version 13. This has no impact on any production code as rake is purely a development dependency.

Update rake from Version 12 to Version 13

---

lib/smart_properties/property_collection.rb
spec/inheritance_spec.rb

Changes the way children register with their parent. The multiple inheritance case was flawed. Ancestors where treated as a linked list when in reality they can be completely independent from one another. Furthermore, the collection with parent collection was recreated on refresh rather than updated.

Child registration

---

lib/smart_properties/property_collection.rb
spec/inheritance_spec.rb

Parents are now registered in reverse order (least significant to most significant). This ensures that a distant ancestor doesn't shadow properties of a closer ancestor.

Reverse order of parent registration

---

lib/smart_properties.rb
spec/inheritance_spec.rb

The parameter passed to `Module.included` is always a `Module` so the check for deciding if the library should inject the `ModuleMethods` was not doing any checks at all.
Since a `Class` is always also a `Module`, the check should check to see if the parameter is not a `Class` instead. This makes sure that `ModuleMethods` is only included into modules and never to classes.
I also added a test to verify these expectations explicitly.

Fix check for including `ModuleMethods`
